### ISSUE TITLE
Cannot download u-boot with plugin on iMX6

### ISSUE THREAD

**Issue by andreascian** [boundarydevices/imx_usb_loader#30]
Dear developers,
I'm working with iMX6, using u-boot with plugin configuration (instead of DCD).
In my experience imx_usb_loader is not working _out-of-the-box_  with this configuration: it hangs right after running the plugin code because (IIUC) once plugin code return control to bootrom, the USB device is removed and plugged in again.

I've solve this issue with a simple workaround: I have two ```mx6_usb_work.conf``` to run in sequence, the first with the following configuration

```
mx6_qsb
hid,1024,0x10000000,1G,0x00907000,0x31000
u-boot.imx:plug
```

and the second defined as

```
mx6_qsb
hid,1024,0x10000000,1G,0x00907000,0x31000
u-boot.imx:load 0x13f00000
u-boot.imx:jump header
```

Between the two I just put a short delay to wait for USB enumeration.

Am I missing something?
Is it possibile the two work into a single configuration file? 

TIA,

Andrea

**Comment by sullin** [comment]
I got the plugin support working with my plugin (https://github.com/ArtecDesign/imx-plugin). We have one concatenated image of plugin+uboot. 
I start the imx_usb_loader just with the image file as argument (no specific config file needed). The imx_usb_loader looks at the imx header and figures out that the first part is a plugin. Then it uploads the plugin. After that, it searches the file for another imx header. It finds the uboot image component imx header and uploads uboot. 
After fixing a bug in the re-connection routine in imx_usb_loader (committed yesterday), everything goes smoothly.

**Comment by andreascian** [comment]
48a85c0b84611c089cf870638fd1241619324b1d fix the problem I have

The latest imx_usb_loader now works with u-boot (2013.04) plugin too (tested on iMX6Q and iMX6DL)

For me the issue is closed, thanks!
