### ISSUE TITLE
Recent Updates Broke imx_usb

### ISSUE THREAD

**Issue by HED-mstarr** [boundarydevices/imx_usb_loader#35]
I am using an i.MX6UL processor with the imx_usb tool.  I was using the tool from commit 349286e25c3fd9b2d31b31e962340123bbc62d44 and everything worked fine. Upon updating to the tool from commit 48a85c0b84611c089cf870638fd1241619324b1d, I am no longer able to boot my board with the same configuration file and same u-boot.imx file.  The imx_usb program output makes it look like it worked, but the board never boots u-boot.

My imx_usb.conf file contains the following:
````
0x15a2:0x007d, imx6.conf
````

My imx6.conf file contains the following:
````
mx6ul
hid,1024,0x80000000,128M,0x00907000,0x31000
u-boot.imx-mfgtool:dcd,plug
u-boot.imx-mfgtool:jump header
````

**Comment by sandsmark** [comment]
The only commit between those I can see that could be relevant would be https://github.com/boundarydevices/imx_usb_loader/commit/6deb910dd0a64267c43e65e95486f975e293823f

try reverting that locally and see if it works again?

**Comment by HED-mstarr** [comment]
I reverted the 6deb910dd0a64267c43e65e95486f975e293823f commit and the imx_usb program worked just as I expected it to.  It looks like this is the commit that is causing the issue.

**Comment by HED-mstarr** [comment]
I have also verified the same issue is occurring on an i.MX53 product I have too, so it is not just the i.MX6UL.

**Comment by HED-mstarr** [comment]
I appear to have found a way to get the new version of imx_usb at 48a85c0b84611c089cf870638fd1241619324b1d to work. I had to modify my mx6.conf file to contain the following (see the original version in the first comment of this issue):
````
mx6ul
hid,1024,0x80000000,128M,0x00907000,0x31000
u-boot.imx-mfgtool:dcd
u-boot.imx-mfgtool:clear_dcd,load,plug,jump header
````

It seems the way I was loading the DCD and bootloader are no longer supported.  It would be great if the format and options of the .conf files were documented to show the proper way to use the file or to document when the .conf format or options change.

**Comment by tkisky** [comment]
On 8/29/2016 11:45 AM, Matthew Starr wrote:
> I appear to have found a way to get the new version of imx_usb at 48a85c0
> <https://github.com/boundarydevices/imx_usb_loader/commit/48a85c0b84611c089cf870638fd1241619324b1d>
> to work. I had to modify my mx6.conf file to contain the following (see the original version in the
> first comment of this issue):
> 
> mx6ul
> hid,1024,0x80000000,128M,0x00907000,0x31000
> u-boot.imx-mfgtool:dcd
> u-boot.imx-mfgtool:clear_dcd,load,plug,jump header |

Does this work ?

mx6ul
hid,1024,0x80000000,128M,0x00907000,0x31000
u-boot.imx-mfgtool:dcd,plug,jump header
____________

When dcd is performed, clear_dcd is also performed. Because rarely will you want to perform the same
dcd twice.
However, since before you used 2 lines, the second line restored its value.

Also, does this work
./imx_usb u-boot.imx-mfgtool

This is how most people use the tool.

> 
> It seems the way I was loading the DCD and bootloader are no longer supported. It would be great if
> the format and options of the .conf files were documented to show the proper way to use the file or
> to document when the .conf format or options change.
>

**Comment by HED-mstarr** [comment]
Both of the .conf file change and the command line only methods recommended worked.

Maybe it was the placing of the "plug" option on the same line as the "dcd" option that was causing the issue.  That is the only other thing I changed.

**Comment by HED-mstarr** [comment]
I recently tried the updated configuration file changes on an i.MX53 product and the imx_usb tool still does not work on it.  It also does not work when just passing a u-boot.imx file to the tool directly on the command line.  It seems in commit 6deb910dd0a64267c43e65e95486f975e293823f, the SDP_WRITE_DCD command was defined and set to an i.MX6 iRAM/OCRAM address of 0x914000.  The valid range for iRAM on the i.MX53 starts at 0xF8006000.

Does anyone know what the proper address is for loading the DCD to iRAM for an i.MX53 when booting over USB using the SDP?

**Comment by gibsson** [comment]
Hi,
The latest patch should fix this issue. The DCD address is now another parameter of the conf file:
https://github.com/boundarydevices/imx_usb_loader/commit/297a57a879925beff9b2d254d328d627f38f4127
Regards,
Gary
