### ISSUE TITLE
Fixes for iMX6UL via UART

### ISSUE THREAD

**Issue by mohicks** [boundarydevices/imx_usb_loader#38]
Hi,

I've been fooling around with bootstrapping the iMX6UL EVK via serial, and I had to make some changes.  The shortlog looks like this:

0554bd7 Add debugmode for UART method
8354f46 Protocol changes required for UART mode to work on i.MX6UL
c86fdf2 Example work file for iMX6UL using UART
aae2439 Add "-N" to skip UART association phase

[patches-imx_usb_loader.zip](https://github.com/boundarydevices/imx_usb_loader/files/485691/patches-imx_usb_loader.zip)

**Comment by gibsson** [comment]
Hi,

Please use the pull-request feature of Github for everybody to be able to review without downloading an archive.

Thanks,
Gary
