### ISSUE TITLE
i.MX5x DCD loading broken

### ISSUE THREAD

**Issue by HED-mstarr** [boundarydevices/imx_usb_loader#40]
i.MX5x DCD loading has not worked since the new DCD_WRITE command was added in commit 6deb910dd0a64267c43e65e95486f975e293823f.  This prevents the imx_usb_loader from being used on processors like i.MX53.

It appears the DCD_WRITE command is only supported on i.MX6 and later processors.  The old method of individually writing each DCD value still needs to be used for the i.MX5x processors.

A fix for this issue is in pull request #39.

**Comment by gibsson** [comment]
Closing this issue since your patch has been accepted: https://github.com/boundarydevices/imx_usb_loader/commit/bb0e5935f5aece19e2b69314a5308fbc96f0d44b
