### ISSUE TITLE
Header not found error when programming SPL on iMX6

### ISSUE THREAD

**Issue by timhjca** [boundarydevices/imx_usb_loader#78]
This happened somewhere between commit (master) 04cd5c487e0f571693ec7b23a40a5d5ad52a38f0 and 869d06beedd11346ed453f26e39321544fcec0ad

I'm getting the following error on the latest master commit:
```
Trying to open device vid=0x15a2 pid=0x0054
Interface 0 claimed
HAB security state: development mode (0x56787856)
== work item
filename output/SPL
load_size 0 bytes
load_addr 0x13f00000
dcd 0
clear_dcd 0
plug 0
jump_mode 3
jump_addr 0x00000000
== end work item
header not found 11000:402000d1, 0
DoIRomDownload failed, err=-22
HAB security state: development mode (0x56787856)
```

This is what it looks like on the older commit:
```
Trying to open device vid=0x15a2 pid=0x0054
Interface 0 claimed
HAB security state: development mode (0x56787856)
== work item
filename output/SPL
load_size 0 bytes
load_addr 0x13f00000
dcd 0
clear_dcd 0
plug 0
jump_mode 3
jump_addr 0x00000000
== end work item

loading binary file(output/SPL) to 00907400, skip=0, fsize=10c00 type=aa

<<<68608, 68608 bytes>>>
succeeded (status 0x88888888)
jumping to 0x00907400
...
```

**Comment by tkisky** [comment]
On 4/25/2018 6:01 AM, timhjca wrote:
> This happened somewhere between commit (master) 04cd5c4
> <https://github.com/boundarydevices/imx_usb_loader/commit/04cd5c487e0f571693ec7b23a40a5d5ad52a38f0>
> and 869d06b
> <https://github.com/boundarydevices/imx_usb_loader/commit/869d06beedd11346ed453f26e39321544fcec0ad>
> 
> I'm getting the following error on the latest master commit:
> 
> |Trying to open device vid=0x15a2 pid=0x0054 Interface 0 claimed HAB security state: development mode
> (0x56787856) == work item filename output/SPL load_size 0 bytes load_addr 0x13f00000 dcd 0 clear_dcd
> 0 plug 0 

jump_mode 3


 jump_addr 0x00000000 == end work item header not found 11000:402000d1, 0
> DoIRomDownload failed, err=-22 HAB security state: development mode (0x56787856) |
> 
> This is what it looks like on the older commit:
> 
> |Trying to open device vid=0x15a2 pid=0x0054 Interface 0 claimed HAB security state: development mode
> (0x56787856) == work item filename output/SPL load_size 0 bytes load_addr 0x13f00000 dcd 0 clear_dcd
> 0 plug 0


 jump_mode 3

____

It is strange that jump_mode isn't 2 here.


Can you send your command line, or mx6_usb_work.conf if that is used. And a link to the file you
are trying to load ?

Thanks
Troy

**Comment by tkisky** [comment]
On 4/25/2018 9:45 AM, Troy Kisky wrote:
> On 4/25/2018 6:01 AM, timhjca wrote:
>> This happened somewhere between commit (master) 04cd5c4
>> <https://github.com/boundarydevices/imx_usb_loader/commit/04cd5c487e0f571693ec7b23a40a5d5ad52a38f0>
>> and 869d06b
>> <https://github.com/boundarydevices/imx_usb_loader/commit/869d06beedd11346ed453f26e39321544fcec0ad>
>>
>> I'm getting the following error on the latest master commit:
>>
>> |Trying to open device vid=0x15a2 pid=0x0054 Interface 0 claimed HAB security state: development mode
>> (0x56787856) == work item filename output/SPL load_size 0 bytes load_addr 0x13f00000 dcd 0 clear_dcd
>> 0 plug 0 
> 
> jump_mode 3
> 
> 
>  jump_addr 0x00000000 == end work item header not found 11000:402000d1, 0
>> DoIRomDownload failed, err=-22 HAB security state: development mode (0x56787856) |
>>
>> This is what it looks like on the older commit:
>>
>> |Trying to open device vid=0x15a2 pid=0x0054 Interface 0 claimed HAB security state: development mode
>> (0x56787856) == work item filename output/SPL load_size 0 bytes load_addr 0x13f00000 dcd 0 clear_dcd
>> 0 plug 0
> 
> 
>  jump_mode 3
> 
> ____
> 
> It is strange that jump_mode isn't 2 here.
> 
> 
> Can you send your command line, or mx6_usb_work.conf if that is used. And a link to the file you
> are trying to load ?
> 
> Thanks
> Troy
> 

Also, check for a "jump header2" in your .conf file, and if found, try "jump header"

I says the because "jump_mode 3" used to be "jump header2", now it is "jump header".
That's why I said it was strange above.


Troy

**Comment by timhjca** [comment]
Switching from `jump header2` to `jump header` did the trick for me. Thanks!
